### ISSUE TITLE
fanout.endpoints and service.fixed

### ISSUE THREAD

**Issue by kristinapathak** [xmidt-org/scytale#60]
Both of these configuration values contain a list of petasoses to fanout to:
`fanout.endpoints`
`service.fixed`

Do we need both? Can we deprecate/remove one?

**Comment by joe94** [comment]
@kristinaspring, I think they do serve different purposes. The latter is a hardcoded list of endpoints for a service discovery component while the first one is a hardcoded list of petasos endpoints specific to scytale. @johnabass did say that "scytale needs a bit of refactoring, and we should probably make the fanout configuration simpler and clearer"

Furthermore, I'm guessing the intent for `service.fixed` is more general than providing potential list of petasos machines.

**Comment by johnabass** [comment]
They service different purposes.

`fanout.endpoints` refers to the specific set of URLs (normally, petasoses) to fanout to.

`service.fixed` is a service discovery configuration option.  It's available in all our servers as a way to manually configure service endpoints instead of letting them be discovered.
